---
title: "RNAscope analysis pipeline development"
output:
  html_document: default
  github_document: default
---
```{r include = FALSE}
### Load data and packages
knitr::opts_chunk$set(fig.width=12, fig.height=8) 

```

```{r, include = FALSE, message = FALSE, warning = FALSE, cache = FALSE}
require(myUtils)
require(rstan)
require(ComplexHeatmap)
source('/home/jovyan/RNAscopeAnalysis/RNAscopeAnalysis.R')
```

```{r, include = TRUE, message = FALSE, warning = FALSE, cache = FALSE}

require(myUtils)
require(rstan)
require(ComplexHeatmap)
source('/home/jovyan/RNAscopeAnalysis/RNAscopeAnalysis.R')

### Simulate data:

RNAscopeGenes1 = c("Slc1a3", "Gad1", "Plp1", "Pdgfra")

# Mean expression profiles in scRNAseq data:
options(stringsAsFactors = FALSE)
counts = readRDS('/home/jovyan/data/Allen/mouse_VISp_2018-06-14_exon+intron_counts-matrix.rds')
rowdata = read.delim('/home/jovyan/data/Allen/mouse_ALM_2018-06-14_genes-rows.csv', sep = ',')
rownames(counts) = rowdata[,1]
counts = counts[,2:dim(counts)[2]]
coldata = read.delim('/home/jovyan/data/Allen/mouse_VISp_2018-06-14_samples-columns.csv', sep = ',')
specific_type = as.character(coldata[,'subclass'])
names(specific_type) = colnames(counts)
classes = coldata[,'class']
names(classes) = colnames(counts)
keep = (classes %in% c('GABAergic', 'Endothelial', 'Glutamatergic', 'Non-Neuronal'))
classes = classes[keep]
specific_type = specific_type[keep]
counts = counts[RNAscopeGenes1,keep]
classes[specific_type == 'Astro'] = 'Astro'
classes[specific_type == 'Endo'] = 'Endo'
classes[specific_type == 'Macrophage'] = 'Macrophage'
classes[specific_type == 'Oligo'] = 'Oligo'
keep = (classes %in% c('Astro', 'Endothelial', 'GABAergic', 'Glutamatergic', 'Macrophage', 'Oligo'))
classes = classes[keep]
specific_type = specific_type[keep]
counts = counts[RNAscopeGenes1,keep]
meanExpr = do.call("cbind", tapply(names(classes), classes, function(x) rowMeans(counts[RNAscopeGenes1,x])))

set.seed(999) # Random number seed
n1 = 10000 # Number of cells to simulate
eta = c(0.8,0.9,1.1,1.2)
size = c(2,2,2,2)
names(eta) = names(size) = RNAscopeGenes1

# RNAscope data:
meanExpr_scope = apply(meanExpr,2, function(x) x*eta+0.001)
celltypes_prob = table(classes)/sum(table(classes))
celltypes = sample(x = names(celltypes_prob), size = n1, prob = celltypes_prob, replace = TRUE)
counts_RNAscope = sapply(celltypes, function(y) sapply(RNAscopeGenes1, function(x) rnbinom(1, size = size[x], mu = meanExpr_scope[x,y])))
```

```{r, include = TRUE, message = FALSE, warning = FALSE, cache = FALSE}
### Plot input data:

genes = rownames(counts_RNAscope)
type = colnames(counts_RNAscope)

require(reshape2)

counts_RNAscope_dataframe = melt(counts_RNAscope, c("Gene", "Celltype"))

p1 = ggplot(counts_RNAscope_dataframe[counts_RNAscope_dataframe$Gene == unique(genes)[[1]],], aes(value, fill = Celltype)) + 
  scale_x_log10() + 
   geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')
p2 = ggplot(counts_RNAscope_dataframe[counts_RNAscope_dataframe$Gene == unique(genes)[[2]],], aes(value, fill = Celltype)) + 
  scale_x_log10() + 
   geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')
p3 = ggplot(counts_RNAscope_dataframe[counts_RNAscope_dataframe$Gene == unique(genes)[[3]],], aes(value, fill = Celltype)) + 
  scale_x_log10() + 
   geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')
p4 = ggplot(counts_RNAscope_dataframe[counts_RNAscope_dataframe$Gene == unique(genes)[[4]],], aes(value, fill = Celltype)) + 
  scale_x_log10() + 
   geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')

require(gridExtra)
do.call(grid.arrange, list(p1,p2,p3,p4))

```


```{r, include = TRUE, message = FALSE, warning = FALSE, cache = FALSE}
### Perform inference on data:
classes = colnames(counts_RNAscope) #c(colnames(counts_RNAscope), colnames(counts_RNAscope1))
countsR = t(counts_RNAscope) #t(cbind(counts_RNAscope, counts_RNAscope1))
meanExprR = t(meanExpr) + 0.001
prior = celltypes_prob
prior = prior[rownames(meanExprR)]
C = dim(countsR)[1]
K = dim(meanExprR)[1]
G = dim(countsR)[2]
eta_prior_params = c(100,100)

stan_rdump(c('prior', 'countsR','meanExprR', 'C', 'K', 'G', 'eta_prior_params'), file = "trial1_model2_data.txt", append = FALSE)
trial1_model2_data <- read_rdump("trial1_model2_data.txt") 

fit1 <- stan(
  file = '/home/jovyan/RNAscopeAnalysis/smFISH_model2.stan',       # Stan program
  data = trial1_model2_data,         # named list of data
  chains = 4,            # number of Markov chains
  warmup = 1000,           # number of warmup iterations per chain
  iter = 2000,             # total number of iterations per chain
  cores = 4,             # number of cores (using 2 just for the vignette)
  refresh = 50,
  algorithm = "NUTS"
)

### Analyse the results:
fit_summary <- summary(fit1)
metrics = accuracyMetrics(fit1, classes, meanExprR, prior, subset = 1:n1)
posterior = as.matrix(fit1)

library("bayesplot")
library("rstanarm")
library("ggplot2")

plot_title <- ggtitle("Posterior distributions of efficiency",
                      "with medians and 80% intervals")
mcmc_areas(posterior[,1:4],
           pars = c("eta[1]", "eta[2]", "eta[3]", "eta[4]"),
           prob = 0.8) + plot_title

```





